/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze */
        post: operations["analyze_analyze_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analyze/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Upload */
        post: operations["analyze_upload_analyze_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Validate */
        post: operations["validate_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActionItem */
        ActionItem: {
            /** Action */
            action: string;
            /** Priority */
            priority: string;
            /** Rationale */
            rationale: string;
        };
        /** Adjustment */
        Adjustment: {
            /** Target Metric Id */
            target_metric_id: string;
            /** Target Display Name */
            target_display_name: string;
            /**
             * Action
             * @enum {string}
             */
            action: "INCREASE" | "DECREASE";
            /**
             * Direction Symbol
             * @enum {string}
             */
            direction_symbol: "+" | "-";
            /** Current Value */
            current_value?: number | null;
            /**
             * Current Value Source
             * @enum {string}
             */
            current_value_source: "submitted" | "not_available";
            /** Target Value */
            target_value: number;
            /** Target Basis */
            target_basis: string;
            /** Delta */
            delta?: number | null;
            /**
             * Priority
             * @enum {string}
             */
            priority: "HIGH" | "MEDIUM" | "LOW";
            /** Rationale */
            rationale: string;
        };
        /** Anomaly */
        Anomaly: {
            /** Anomaly Id */
            anomaly_id: string;
            /** Metric Id */
            metric_id: string;
            /** Metric Display Name */
            metric_display_name: string;
            /** Category */
            category: string;
            /** Severity Score */
            severity_score: number;
            severity_label: components["schemas"]["SeverityLabel"];
            deviation: components["schemas"]["DeviationDetail"];
            trend: components["schemas"]["TrendDetail"];
            /** Correlated Anomalies */
            correlated_anomalies: string[];
            /** Noise Confidence */
            noise_confidence: number;
            /** Context Tags */
            context_tags: string[];
            /** Natural Language Summary */
            natural_language_summary: string;
        };
        /** AnomalyReport */
        AnomalyReport: {
            /**
             * $Schema
             * @default anomaly_report_v1
             */
            $schema: string;
            /** Company Id */
            company_id: string;
            sector_id: components["schemas"]["SectorId"];
            /**
             * Analysis Timestamp
             * Format: date-time
             */
            analysis_timestamp: string;
            reporting_period: components["schemas"]["ReportingPeriod"];
            company_profile_summary: components["schemas"]["CompanyProfileSummary"];
            /** Overall Health Score */
            overall_health_score?: number | null;
            /**
             * Anomalies
             * @default []
             */
            anomalies: components["schemas"]["Anomaly"][];
            /**
             * Non Anomalous Highlights
             * @default []
             */
            non_anomalous_highlights: components["schemas"]["HealthyHighlight"][];
            refusal?: components["schemas"]["RefusalDetail"] | null;
            metadata: components["schemas"]["ReportMetadata"];
        };
        /**
         * ApiResponse
         * @description Envelope. Identical shape whether sync or polled — so we can switch
         *     without touching the frontend.
         */
        ApiResponse: {
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "running" | "failed" | "refused";
            result?: components["schemas"]["EnrichedReport"] | null;
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ParseWarning"][];
            error?: components["schemas"]["ErrorCode"] | null;
            timings?: components["schemas"]["Timings"] | null;
        };
        /** Body_analyze_upload_analyze_upload_post */
        Body_analyze_upload_analyze_upload_post: {
            /** File */
            file: string;
            /** Metadata */
            metadata: string;
            /** Mapping Overrides */
            mapping_overrides?: string | null;
        };
        /** Body_validate_validate_post */
        Body_validate_validate_post: {
            /** File */
            file: string;
            /** Metadata */
            metadata: string;
        };
        /** CompanyInput */
        CompanyInput: {
            /** Company Id */
            company_id: string;
            sector_id: components["schemas"]["SectorId"];
            company_metadata: components["schemas"]["CompanyMetadata"];
            reporting_period: components["schemas"]["ReportingPeriod"];
            /** Metrics */
            metrics: components["schemas"]["MetricEntry"][];
            /** Raw Text Context */
            raw_text_context?: string | null;
        };
        /** CompanyMetadata */
        CompanyMetadata: {
            /** Name */
            name: string;
            /** Founded Year */
            founded_year?: number | null;
            /** Employee Count */
            employee_count: number;
            /** Annual Revenue */
            annual_revenue?: number | null;
            revenue_band: components["schemas"]["RevenueBand"];
            /** Region */
            region: string;
        };
        /** CompanyProfileSummary */
        CompanyProfileSummary: {
            revenue_band: components["schemas"]["RevenueBand"];
            /** Employee Count */
            employee_count: number;
            /** Region */
            region: string;
        };
        /** DataPoint */
        DataPoint: {
            /** Period */
            period: string;
            /** Value */
            value: number;
            /**
             * Interpolated
             * @default false
             */
            interpolated: boolean;
        };
        /** DeviationDetail */
        DeviationDetail: {
            /** Observed Current */
            observed_current: number;
            /** Expected Value */
            expected_value: number;
            /** Expected Std */
            expected_std: number;
            /** Z Score */
            z_score: number;
            /** Percentile */
            percentile: number;
            direction: components["schemas"]["DeviationDirection"];
        };
        /**
         * DeviationDirection
         * @enum {string}
         */
        DeviationDirection: "above_expected" | "below_expected" | "as_expected";
        /** EnrichedReport */
        EnrichedReport: {
            /**
             * $Schema
             * @default enriched_report_v1
             */
            $schema: string;
            anomaly_report: components["schemas"]["AnomalyReport"];
            /**
             * Prescriptions
             * @default []
             */
            prescriptions: components["schemas"]["Prescription"][];
            /**
             * Anomaly Clusters
             * @default []
             */
            anomaly_clusters: string[][];
            /**
             * Matched Cases
             * @default []
             */
            matched_cases: components["schemas"]["MatchedCase"][];
            narrative?: components["schemas"]["Narrative"] | null;
            metadata: components["schemas"]["EnrichmentMetadata"];
        };
        /**
         * EnrichmentMetadata
         * @description degraded_reason — C2-PROPOSED v1.2, additive and optional. Not in the
         *     signed contract shape (Contract §6.2); flagged for announcement to C3
         *     alongside O7 (EnrichedReport sign-off still pending).
         *
         *     Deliberately Optional[str], not an enum: this field can be set by either
         *     side (C2 when it wraps a bare AnomalyReport after a C1/C3 failure; C3
         *     itself per Contract §6.7, e.g. an LLM failure it handles internally with
         *     no exception ever reaching C2). An enum would turn an unrecognised value
         *     from the other component into a ValidationError — a hard failure exactly
         *     where degradation was supposed to be graceful.
         *
         *     Conventional vocabulary (not enforced):
         *         C2 sets: c3_timeout | c3_failed | c3_contract_violation
         *         C3 sets: llm_failed | llm_timeout | case_match_failed
         *     Unknown values are logged and rendered generically, never rejected.
         */
        EnrichmentMetadata: {
            /** Llm Model */
            llm_model?: string | null;
            /** Llm Tokens Used */
            llm_tokens_used?: number | null;
            /** Processing Time Ms */
            processing_time_ms: number;
            /** Cases Searched */
            cases_searched: number;
            /** Cases Matched */
            cases_matched: number;
            /**
             * Unmatched Anomaly Ids
             * @default []
             */
            unmatched_anomaly_ids: string[];
            /**
             * Degraded
             * @default false
             */
            degraded: boolean;
            /** Degraded Reason */
            degraded_reason?: string | null;
        };
        /**
         * ErrorCode
         * @description Error-code vocabulary for ApiResponse.error (Phase1-Plan T1.5). C2-owned
         *     and always self-assigned — never parsed from an external component's
         *     output — so unlike EnrichmentMetadata.degraded_reason this is safe to
         *     type as an enum rather than a bare string.
         * @enum {string}
         */
        ErrorCode: "VALIDATION_ERROR" | "C1_TIMEOUT" | "C1_FAILED" | "C1_UNAVAILABLE" | "C3_TIMEOUT" | "C3_FAILED" | "C3_CONTRACT_VIOLATION" | "INTERNAL_ERROR";
        /**
         * Granularity
         * @enum {string}
         */
        Granularity: "monthly" | "quarterly" | "annual";
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthyHighlight */
        HealthyHighlight: {
            /** Metric Id */
            metric_id: string;
            /** Status */
            status: string;
            /** Percentile */
            percentile: number;
            /** Note */
            note: string;
        };
        /** InferredMetadata */
        InferredMetadata: {
            /** Granularity */
            granularity?: string | null;
            /**
             * Periods
             * @default 0
             */
            periods: number;
            /** Shape */
            shape?: ("wide" | "transposed" | "form") | null;
            /** Revenue Band */
            revenue_band?: string | null;
        };
        /**
         * MappingProposal
         * @description One resolved column from an uploaded file.
         */
        MappingProposal: {
            /** Source Label */
            source_label: string;
            /** Resolved Metric Id */
            resolved_metric_id?: string | null;
            /**
             * Match Type
             * @enum {string}
             */
            match_type: "exact" | "alias" | "normalized" | "unresolved";
            /** Unit Warning */
            unit_warning?: string | null;
            /**
             * Candidates
             * @default []
             */
            candidates: string[];
            /**
             * Sample Values
             * @default []
             */
            sample_values: number[];
        };
        /** MatchedCase */
        MatchedCase: {
            /** Case Id */
            case_id: string;
            /** Cluster Index */
            cluster_index: number;
            /** Similarity Score */
            similarity_score: number;
            /** Problem Description */
            problem_description: string;
            /** Root Causes */
            root_causes: string[];
            /** Recommended Actions */
            recommended_actions: string[];
        };
        /** MetricEntry */
        MetricEntry: {
            /** Metric Id */
            metric_id: string;
            granularity: components["schemas"]["Granularity"];
            /** Values */
            values: components["schemas"]["DataPoint"][];
            /**
             * Confidence
             * @default 1
             */
            confidence: number;
        };
        /** Narrative */
        Narrative: {
            /** Situation Summary */
            situation_summary: string;
            /** Likely Root Causes */
            likely_root_causes: string[];
            /** Prioritized Actions */
            prioritized_actions: components["schemas"]["ActionItem"][];
            /** Positives */
            positives: string[];
        };
        /** ParseWarning */
        ParseWarning: {
            code: components["schemas"]["ParseWarningCode"];
            /** Metric Id */
            metric_id?: string | null;
            /** Message */
            message: string;
        };
        /**
         * ParseWarningCode
         * @description Warning-code vocabulary, defined now so Phase 2 (parsing) and Phase 3
         *     (frontend) agree without a second conversation (Phase0-Plan T0.3).
         * @enum {string}
         */
        ParseWarningCode: "UNKNOWN_METRIC" | "UNIT_SCALE_SUSPECT" | "OUT_OF_RANGE" | "SHORT_SERIES" | "INTERPOLATED_POINTS" | "SECTOR_MISMATCH" | "AMBIGUOUS_MAPPING" | "SCHEMA_VALIDATION_ERROR" | "DATE_TRUNCATED" | "TWO_DIGIT_YEAR_FUTURE" | "AMBIGUOUS_NUMBER_FORMAT" | "MIXED_GRANULARITY" | "AMBIGUOUS_SHAPE" | "SERIES_TRIMMED" | "INTERPOLATION_HEAVY" | "CONSTANT_SERIES" | "SPARSE_SERIES" | "DUPLICATE_PERIOD" | "REFUSAL_LIKELY";
        /** Prescription */
        Prescription: {
            /** Anomaly Id */
            anomaly_id: string;
            /** Prescribed Adjustments */
            prescribed_adjustments: components["schemas"]["Adjustment"][];
            /** Prescription Summary */
            prescription_summary: string;
        };
        /**
         * RefusalDetail
         * @description UNVERIFIED — confirm against C1 repo. Only `reason` is confirmed against
         *     C1's source; `message` and `suggested_resolution` are C2's provisional
         *     additions (Contract §5.1, O13). `extra="allow"` is mandatory per the
         *     contract so real fields we failed to predict aren't silently dropped.
         *
         *     C2's rendering logic must not depend on `message` being present — it
         *     generates fallback text from `reason` plus the original CompanyInput.
         *     Both provisional fields are therefore Optional even though the contract's
         *     prose shows `message` as a bare `str`.
         */
        RefusalDetail: {
            reason: components["schemas"]["RefusalReason"];
            /** Message */
            message?: string | null;
            /** Suggested Resolution */
            suggested_resolution?: string | null;
        } & {
            [key: string]: unknown;
        };
        /**
         * RefusalReason
         * @enum {string}
         */
        RefusalReason: "no_metrics_submitted" | "low_data_confidence" | "insufficient_periods" | "contradictory_evidence";
        /** ReportMetadata */
        ReportMetadata: {
            /** Model Version */
            model_version: string;
            /** Synthetic Profile Version */
            synthetic_profile_version?: string | null;
            /** Metrics Analyzed */
            metrics_analyzed: number;
            /** Metrics With Anomalies */
            metrics_with_anomalies: number;
            /** Metrics With Missing Data */
            metrics_with_missing_data: number;
            /**
             * Skipped Metrics
             * @default []
             */
            skipped_metrics: string[];
            /** Processing Time Ms */
            processing_time_ms: number;
        };
        /** ReportingPeriod */
        ReportingPeriod: {
            type: components["schemas"]["Granularity"];
            /**
             * Start
             * Format: date
             */
            start: string;
            /**
             * End
             * Format: date
             */
            end: string;
        };
        /**
         * RevenueBand
         * @enum {string}
         */
        RevenueBand: "<1M" | "1M-10M" | "10M-100M" | ">100M";
        /**
         * SectorId
         * @enum {string}
         */
        SectorId: "TECH_SAAS" | "RETAIL";
        /**
         * SeverityLabel
         * @enum {string}
         */
        SeverityLabel: "INFO" | "WARNING" | "CRITICAL" | "SEVERE";
        /**
         * Timings
         * @description Wall-clock time C2's orchestrator spent per stage — distinct from each
         *     stage's own self-reported processing_time_ms (ReportMetadata /
         *     EnrichmentMetadata), which measures only that component's internal
         *     computation, not thread-pool or dispatch overhead.
         */
        Timings: {
            /** C1 Ms */
            c1_ms?: number | null;
            /** C3 Ms */
            c3_ms?: number | null;
            /** Total Ms */
            total_ms: number;
        };
        /** TrendDetail */
        TrendDetail: {
            direction: components["schemas"]["TrendDirection"];
            /** Slope */
            slope?: number | null;
            /** Acceleration */
            acceleration?: number | null;
            /** Periods Deviating */
            periods_deviating?: number | null;
            /** Values Over Time */
            values_over_time?: components["schemas"]["TrendPoint"][] | null;
        };
        /**
         * TrendDirection
         * @enum {string}
         */
        TrendDirection: "improving" | "stable" | "deteriorating";
        /** TrendPoint */
        TrendPoint: {
            /** Period */
            period: string;
            /** Value */
            value: number;
            /** Z Score */
            z_score: number;
        };
        /**
         * ValidateResponse
         * @description POST /validate's response shape (Phase2-Plan T2.6). Distinct from
         *     ParseResult — it never carries a company_input (validate stops before
         *     building one) and adds `inferred`/`ready`, which ParseResult has no use
         *     for elsewhere.
         */
        ValidateResponse: {
            /**
             * Proposals
             * @default []
             */
            proposals: components["schemas"]["MappingProposal"][];
            /**
             * Warnings
             * @default []
             */
            warnings: components["schemas"]["ParseWarning"][];
            /**
             * Blocking Errors
             * @default []
             */
            blocking_errors: string[];
            /**
             * @default {
             *       "periods": 0
             *     }
             */
            inferred: components["schemas"]["InferredMetadata"];
            /**
             * Ready
             * @default false
             */
            ready: boolean;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    analyze_analyze_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompanyInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    analyze_upload_analyze_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_upload_analyze_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    validate_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_validate_validate_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
